---
name: Deploy

permissions:
  contents: write

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.6'
        bundler-cache: true
    - name: Update robots.txt
      run: |
        if curl 'https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/refs/heads/main/robots.txt' > robots-list.txt
          then echo "Using ai-robots-txt's bot list..."; mv -f robots-list.txt robots.txt
          else echo "ai-robots-txt not available, using bots.yml..."
        fi
        echo "Done!"
    - name: Build site
      run: |
        bundle exec jekyll build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.7.3
      with:
        folder: _site
